services:
  - type: web
    name: smipe
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: WEB_CONCURRENCY
        value: 2
    disk:
      name: smipe-data
      mountPath: /data
      sizeGB: 1
